### ISSUE TITLE
GUI problems under windows

### ISSUE THREAD

**Issue by kishorkk91** [Ragin-LundF/k8s-jcasc-management-go#9]
![CPU](https://user-images.githubusercontent.com/59603187/86122141-9512e580-bad7-11ea-9eda-85bb228ceb56.PNG)
![GPU](https://user-images.githubusercontent.com/59603187/86122143-95ab7c00-bad7-11ea-8957-e9101dde5b38.PNG)
![K8SMGMT](https://user-images.githubusercontent.com/59603187/86122145-95ab7c00-bad7-11ea-97f9-5f8673ff290b.PNG)

**Comment by Ragin-LundF** [comment]
I've talked to the developers if fyne and they said, that the issue should be solved in the current branch. I've updated the dependencies again.
Can you please pull the change and validate, if it is now working?

**Comment by kishorkk91** [comment]
Unfortunately not fixed, still the same problem!! Even after pulling the recent changes of Master and Develop. Also cross checked with my teammates.

**Comment by Ragin-LundF** [comment]
Can you please try to run the application with:
`go run -tags no_native_menus k8s-jcasc-mgmt.go`

Please do also a `go get -u` to update everything (or try to delete `$GOROOT/pkg/mod` directory, that GO has to fetch all dependencies in the latest version.

After you have tested it you can revert the `go.mod` and `go.sum` file.

**Comment by kishorkk91** [comment]
Tried updating but still the same problem.

**Comment by Ragin-LundF** [comment]
There were some issues with the Go proxy server. Fyne has released a new 1.3.2 version to solve the issue. Maybe it happened to you...
Please try to update the project and clean your cache with:

```bash
go clean -cache -modcache -i -r
```

I also recognized, that under Windows some stuff is in `C:\Users\<user>\AppData\Local\Temp`.
Please try to delete the content of this directory (some files/directories are undeletable...simply skip them all).

After that try to recompile/re-run the application and please report if it solved the issue.

**Comment by kishorkk91** [comment]
this issue not solved yet !!, pulled latest update, and cache clean/Temp deletion didnt help. However, last week I was able to update NVIDIA graphics driver and requested our IT services to update Intel HD 530 graphics drivers(Currently really old-2017). As soon as I get latest drivers then I can test again.
Also tried to re-run application after changing version from **Go 1.14.4** to **Go 1.15beta1**  and vice-a-versa but no positive news yet.  

![image](https://user-images.githubusercontent.com/59603187/87277507-b6fe6600-c4e2-11ea-8d1a-0cfd4e5e2c49.png)

**Comment by kishorkk91** [comment]
**Finally some positive news!**   Graphics problem solved and tool works fine after driver update.


![image](https://user-images.githubusercontent.com/59603187/87303182-03fa3080-c513-11ea-868d-5847119d0ffb.png)

**Comment by Ragin-LundF** [comment]
Ah cool. Great news ;). What a hassle ;).
If something else will fail please simply open an issue or contact me ;).

**Comment by kishorkk91** [comment]
Yes sure,,, I will keep that in mind : )
